<?php
 if(!defined('IN_BMC')) 
	die("Access Denied!");


$countries = array(
"Afghanistan", 
"Albania", 
"Algeria", 
"American Samoa", 
"Andorra", 
"Angola", 
"Anguilla", 
"Antarctica", 
"Antigua and Barbuda", 
"Argentina", 
"Armenia", 
"Aruba", 
"Australia", 
"Austria", 
"Azerbaijan", 
"Bahamas", 
"Bahrain", 
"Bangladesh", 
"Barbados", 
"Belarus", 
"Belgium", 
"Belize", 
"Benin", 
"Bermuda", 
"Bhutan", 
"Bolivia", 
"Bosnia and Herzegovina", 
"Botswana", 
"Bouvet Island", 
"Brazil", 
"Brunei Darussalam", 
"Bulgaria", 
"Burkina Faso", 
"Burundi", 
"Cambodia", 
"Cameroon", 
"Canada", 
"Cape Verde", 
"Cayman Islands", 
"Central African Republic", 
"Chad", 
"Chile", 
"China", 
"Christmas Island", 
"Cocos Islands", 
"Colombia", 
"Comoros", 
"Congo", 
"Cook Islands", 
"Costa Rica", 
"Cote d'Ivoire", 
"Croatia", 
"Cuba", 
"Cyprus", 
"Czech Republic", 
"Denmark", 
"Djibouti", 
"Dominica", 
"Dominican Republic", 
"Ecuador", 
"Egypt", 
"El Salvador", 
"Equatorial Guinea", 
"Eritrea", 
"Estonia", 
"Ethiopia", 
"Falkland Islands", 
"Faroe Islands", 
"Fiji", 
"Finland", 
"France", 
"French Guiana", 
"French Polynesia", 
"Gabon", 
"Gambia", 
"Georgia", 
"Germany", 
"Ghana", 
"Gibraltar", 
"Greece", 
"Greenland", 
"Grenada", 
"Guadeloupe", 
"Guam", 
"Guatemala", 
"Guinea", 
"Guinea-Bissau", 
"Guyana", 
"Haiti", 
"Honduras", 
"Hong Kong", 
"Hungary", 
"Iceland", 
"India", 
"Indonesia", 
"Iran", 
"Iraq", 
"Ireland", 
"Isle of Man", 
"Israel", 
"Italy", 
"Jamaica", 
"Japan", 
"Jordan", 
"Kazakhstan", 
"Kenya", 
"Kiribati", 
"Kuwait", 
"Kyrgyzstan", 
"Laos", 
"Latvia", 
"Lebanon", 
"Lesotho", 
"Liberia", 
"Libya", 
"Liechtenstein", 
"Lithuania", 
"Luxembourg", 
"Macao", 
"Madagascar", 
"Malawi", 
"Malaysia", 
"Maldives", 
"Mali", 
"Malta", 
"Marshall Islands", 
"Martinique", 
"Mauritania", 
"Mauritius", 
"Mayotte", 
"Mexico", 
"Micronesia", 
"Moldova", 
"Monaco", 
"Mongolia", 
"Montenegro", 
"Montserrat", 
"Morocco", 
"Mozambique", 
"Myanmar", 
"Namibia", 
"Nauru", 
"Nepal", 
"Netherlands", 
"Netherlands Antilles", 
"New Caledonia", 
"New Zealand", 
"Nicaragua", 
"Niger", 
"Nigeria", 
"Norfolk Island", 
"North Korea", 
"Norway", 
"Oman", 
"Pakistan", 
"Palau", 
"Palestinian Territory", 
"Panama", 
"Papua New Guinea", 
"Paraguay", 
"Peru", 
"Philippines", 
"Pitcairn", 
"Poland", 
"Portugal", 
"Puerto Rico", 
"Qatar", 
"Romania", 
"Russian Federation", 
"Rwanda", 
"Saint Helena", 
"Saint Kitts and Nevis", 
"Saint Lucia", 
"Samoa", 
"San Marino", 
"Sao Tome and Principe", 
"Saudi Arabia", 
"Senegal", 
"Serbia", 
"Seychelles", 
"Sierra Leone", 
"Singapore", 
"Slovakia", 
"Slovenia", 
"Solomon Islands", 
"Somalia", 
"South Africa", 
"South Georgia", 
"South Korea", 
"Spain", 
"Sri Lanka", 
"Sudan", 
"Suriname", 
"Swaziland", 
"Sweden", 
"Switzerland", 
"Syrian Arab Republic", 
"Taiwan", 
"Tajikistan", 
"Tanzania", 
"Thailand", 
"Republic of Macedonia", 
"Timor-Leste", 
"Togo", 
"Tokelau", 
"Tonga", 
"Trinidad and Tobago", 
"Tunisia", 
"Turkey", 
"Turkmenistan", 
"Tuvalu", 
"Uganda", 
"Ukraine", 
"United Arab Emirates", 
"United Kingdom", 
"United States", 
"Uruguay", 
"Uzbekistan", 
"Vanuatu", 
"Vatican City", 
"Venezuela", 
"Vietnam", 
"Wallis and Futuna", 
"Western Sahara", 
"Yemen", 
"Zambia", 
"Zimbabwe");




	echo "<select name=\"country\" id=\"country\" size=\"1\" onchange=\"changed=true;\">";
//  	echo '<option value=""> -- choose --</option>'; CRITICAL
	foreach($countries as $temp){
	  	echo '<option value="'.$temp.'">'.$temp.'</option>';
	}
	echo "</select><br/>\n";

